- next_rails.gemspec
Rubygems.org is currently linking a bad Homepage, update gemspec so that the next gem release will fix that.
> Update homepage in gemspec

- lib/next_rails/gem_info.rb
- spec/ten_years_rails/gem_info_spec.rb
Hi there, 
I believe it would be best to not use `actionview` at all in this gem. It causes problems and narrows our options in terms of older rubies/rails apps. 
So this PR drops any hint of `actionview` for this tool and it solves #21. 
Please check it out. 
Thanks!
> Remove any traces of `actionview`

- CODE_OF_CONDUCT.md
- pull_request_template.md
This PR adds the `CODE_OF_CONDUCT.md` and `pull_request_template.md` files. The PR template has a reminder to update the CHANGELOG.
> [CHORE]: Add Code of Conduct and PR template

- lib/deprecation_tracker.rb
- spec/deprecation_tracker_spec.rb
Description:
Fixes: https://github.com/fastruby/next_rails/issues/13
It checks if the path passed as the shitlist file exists or not. If it does not exist, it creates the directory.
> if shitlist path does not exist, fix the failure with ENOENT

- README.md
- exe/next_rails
Closes https://github.com/fastruby/next_rails/issues/15
Description:
There are a few executables or command-line options already present for example bundle_report, deprecations, next, 
but none of them really reflects the whole gem as such. 
So I have added a new executable called `next_rails` and we can use it like `next_rails --version`.
This is a general convention followed by libraries that provide options like version, 
for ex: puma gem provides `puma --version` as a command-line option.
I have also updated the READme so the documentation covers the mention of this new option.
> added 'next_rails' exe to support cli option for version

- README.md
- lib/deprecation_tracker.rb
- spec/deprecation_tracker_spec.rb
Description:
This PR adds a `track_minitest` method that does something kinda similar to `track_rspec` but for Minitest.
I updated the README to show how to use this too, it's slightly different.
I tested this using this sample app that has some tests for both RSpec and Minitest https://github.com/fastruby/js-coverage-sample-app.
- I added the config described in the README
- I added some code that I know would trigger a deprecation warning (call `ActiveRecord::Base.allow_unsafe_raw_sql` inside tests)
- I ran both `rails spec` and `rails test:all`
- Verified the `support/...shitlist.json` files are there for `/test` and `/spec` with the same content
> Add support to use DeprecationTracker with Minitest

- pull_request_template.md
This closes issue #45 
Description:
This updates the link to the code of conduct in the PR template. I'm not sure how this can be tested, I think it has to be merged first. 
> Update the code of conduct link in PR template

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This closes issue #14 
Description:
Added templates for bug reports and feature requests for Issues on GitHub. I based these templates off of what is being user in the fastruby project: dotenv_validator
> Add FEATURE REQUEST and BUG REPORT templates

- lib/deprecation_tracker.rb
Description:
This PR fixes #23 by making the last 2 arguments for the custom behavior optional.
Before Rails 5.2, the behavior only supported 2 arguments and ActiveSupport would call the behavior with only 2 arguments (then the error `given 2, expected 4`). By making the unused arguments optional the code works fine in older Rails versions.
Behaviors in Rails < 5.2: https://github.com/rails/rails/blob/5-1-stable/activesupport/lib/active_support/deprecation/behaviors.rb#L12
Behaviors since Rails >= 5.2: https://github.com/rails/rails/blob/5-2-stable/activesupport/lib/active_support/deprecation/behaviors.rb#L14
I tested this by creating a Rails 5.1.7 project, adding next_rails to track deprecations and manually added a deprecation warning both before and after this change and I can confirm …
> Make behavior arguments optional

- CHANGELOG.md
- lib/next_rails/bundle_report.rb
- lib/next_rails/gem_info.rb
**Description:**
This PR changes how we check the compatibility of gems. Currently, if the current version of a gem is not compatible with the desired Rails version, we check if the latest available version of that gem is compatible with Rails.
This is a problem, because the latest version may not be compatible with the desired Rails version, but there might be other versions between the current and the latest that are compatible.
This PR updates the compatibility check to check all versions from the latest to the current until it finds a compatible version.
**How I tested this:**
I really don't know how to add an automated test for this, it relies a lot on external data.
What I did to test this was:
- created a new Rails 4.2.11 app
- changed the version of coffee-rails from 4.1.0 to …
> Find latest compatible version when checking compatibility

- CHANGELOG.md
Description:
The current CHANGELOG  does not have an entry for the last released version of the gem i.e 1.1.0.
All the changes in 1.1.0 are mentioned under the `# main [(unreleased)]` heading which is incorrect.
So, I have added an entry for 1.1.0 and put everything that belonged in that release under it and added a 
`# main [(unreleased)]` at the top for future changes.
I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md).
> update CHANGELOG with info tagged under correct released versions

- .github/workflows/main.yml
- CHANGELOG.md
- lib/deprecation_tracker.rb
- lib/next_rails/bundle_report.rb
- lib/next_rails/gem_info.rb
- next_rails.gemspec
This PR adds support for older Ruby 2 versions.
Things I changed:
- added explicit default values for keyword arguments (implicit values not supported in older rubies)
- limit `rexml` version, newer versions use implicit default values for keywords arguments (related to the previous change)
- use the `<<-` heredoc syntax instead of `<<~`, the `~` version didn't exist in older rubies (since what it does is remove the indentation, I removed the indentation in the code instead)
- use `Object.extend` if `Object.prepend` is not a valid method, it was added in Ruby 2.1.10 https://apidock.com/ruby/v2_1_10/Module/prepend
- replace a call to `Array#to_h`, since that method was added in Ruby 2.1.10 https://apidock.com/ruby/v2_1_10/Array/to_h
- configured the github actions to run the tests with …
> Support Ruby >= 2.0.0

- CHANGELOG.md
- lib/next_rails/version.rb
> Release v1.2.0

- CHANGELOG.md
- spec/spec_helper.rb
Description:
SimpleCov must be loaded as the very first thing
If not, coverage reporting and calculation will be inaccurate. This is a known gotcha with SimpleCov.
Fixes https://github.com/fastruby/next_rails/issues/65
I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md).
> SimpleCov must be loaded as the very first thing

- lib/next_rails/gem_info.rb
- spec/ten_years_rails/gem_info_spec.rb
`bundle_report outdated` is currently failing with "undefined local variable or method `latest_version'".
We need to define latest_version method to filter out up-to-date gems.
> Fix for up_to_date? method

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.md
- pull_request_template.md
Description:
Simply updates our templates for bug fixes, feature requests and pull requests, as agreed upon in [this RFC](https://github.com/fastruby/RFCs/blob/main/2021-10-13-github-templates.md)
I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md).
> [OSS-64] Add templates for bug report, feature request and pull request

- lib/next_rails/gem_info.rb
- spec/next_rails/gem_info_spec.rb
- Adds use of safe access operator in `GemInfo#state` conditional expression
- This fix is related to issue [#77](https://github.com/fastruby/next_rails/issues/77)
- Without this safe access operator the `else` part of this condition is never reached when `@latest_compatible_version` is `nil`. 
I will say I'm not completely clear on the logic in `#find_latest_compatible`. I don't know enough about the shape of the spec objects and the edge cases surrounding them. It appears to me that the error state is caused when there are specs found by the `Gem::SpecFetcher` but none of them are compatible with the version of Rails given. This will execute `#find_latest_compatible` but never set the `@latest_compatible_version` instance variable. It's a bit confusing as there is a null object pattern …
> Fix bundle report compatibility error

- README.md
Following the README.md it says we should have a `deprecations.shitlist.json` file but it actually needs a `deprecation_warning.shitlist.json` file name.
Make the README match the actual file name.
I tested on a local project changing the name to `deprecation_warning.shitlist.json` and it works.
Error trace
```bash
root@5f3850ba4310:/app# deprecations info
Traceback (most recent call last):
3: from /usr/local/bundle/bin/deprecations:23:in `<main>'
2: from /usr/local/bundle/bin/deprecations:23:in `load'
1: from /usr/local/bundle/gems/next_rails-1.2.1/exe/deprecations:93:in `<top (required)>'
/usr/local/bundle/gems/next_rails-1.2.1/exe/deprecations:93:in `read': No such file or directory @ rb_sysopen - spec/support/deprecation_warning.shitlist.json (Errno::ENOENT)
```
**I will abide by the …
> Update deprecation warning file name

- lib/next_rails/bundle_report.rb
This PR fixes #90
The oldest available version of ERB (2.2.0) was already deprecating these positional parameters but that warning was behind a CLI flag. In newer versions this deprecation is displayed without the need of the CLI flag.
2.2.0 https://github.com/ruby/erb/blob/v2.2.0/lib/erb.rb#L815
2.2.1 https://github.com/ruby/erb/blob/v2.2.1/lib/erb.rb#L816
This change is backwards compatible because 2.2.0 is the oldest available version of ERB and it already prefers keyword arguments over positional arguments
I ran next_rails before and after this change in Ruby 3.1.3 (which uses ERB 2.2.3)
Before:
```
bundle_report --rails-version=7.1
/home/ariel/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/erb.rb:814: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use …
```
> Pass trim_mode keyword arguments instead of positional argument to ERB.new

- lib/next_rails/gem_info.rb
This PR fixes #89
Output on a test project I was using with Rails 6
Before:
```
bundle_report compatibility --rails-version=7.0 
=> Incompatible with Rails 7.0 (with new versions that are compatible):
These gems will need to be upgraded before upgrading to Rails 7.0.
actionmailbox 6.0.4 - upgrade to 7.0.0
actiontext 6.0.4 - upgrade to 7.0.0
dotenv-rails 2.7.5 - upgrade to 2.8.1
ombu_labs-hubspot 0.1.0 (loaded from git) - upgrade to 0.1.1
ombu_labs-notifications 0.1.0 (loaded from git) - upgrade to 0.1.2
5 gems incompatible with Rails 7.0
```
After:
```
bundle_report compatibility --rails-version=7.0 
=> Incompatible with Rails 7.0 (with new versions that are compatible):
These gems will need to be upgraded before upgrading to Rails 7.0.
dotenv-rails 2.7.5 - upgrade to 2.8.1 …
```
> Ignore actionmailbox and actiontext rails gems from bundle report

- lib/deprecation_tracker.rb
I encountered this error after adding `next_rails` to the project we're using in the Rails upgrade workshop. This error did not happen before adding `next_rails`
I traced it to a `warn` call in a gem being used by the project. The `warn` call in Rails 3 has a `category` keyword argument that our monkey patch in `next_rails` is not supporting https://github.com/countries/country_select/blob/7e73c4cc465aa61c268867b985837f2a126cffdc/lib/country_select/country_select_helper.rb#L10
Tested locally. Making this change resolves the error.
> Update the `warn` method signature to support Rails 3.1

- lib/next_rails.rb
- spec/next_rails_spec.rb
Reference #97
This is trying to solve what [Ariel found in this comment.](https://github.com/fastruby/next_rails/pull/97#discussion_r1221539373)
> Add Module attribute and File check

- .github/workflows/main.yml
When the tests start to run, the Ruby 2.2 tests have a bug that makes it fail and that produces a cancellation of all the other jobs in that matrix.
Seems to be a known issue and this PR adds the proposed workaround from this bug report https://github.com/ruby/setup-ruby/issues/496#issuecomment-1520667671 running 2.2 and older in a previous version of Ubuntu instead of Ubuntu latest
You can see in the other 2 latest PRs that it was failing for 2.2 always, and I ran all the versions manually for https://github.com/fastruby/next_rails/pull/100 and 2.2 keeps failing
> Fix Ruby 2.2 setup in github action

- CHANGELOG.md
- lib/next_rails/bundle_report.rb
- next_rails.gemspec
- spec/bundle_report_spec.rb
The bundler report compatibility command didn't work in old ERB version. This PR adds a test that exercises that line and also the fix calling `ERB.new` with different arguments depending on the ERB version.
This issue https://github.com/fastruby/next_rails/issues/99
I think this is the same issue https://github.com/fastruby/next_rails/issues/96
Added automated tests, without this change it fails in Ruby 2.3
> Support ERB syntax in old Ruby versions

- next_rails.gemspec
- spec/next_rails_spec.rb
- spec/spec_helper.rb
Is there any reason you want to still using the gem?
Remove `climate_control` as a dependency we are implementing the `stub_const` method.
Avoid having another dependency gem because old Ruby versions are complaining about it.
Wishing the RSpec tests
> Replace climate_control gem with stub_const

- CHANGELOG.md
- exe/deprecations
- lib/deprecation_tracker.rb
- lib/next_rails/bundle_report.rb
- next_rails.gemspec
- spec/bundle_report_spec.rb
The Colorize dependency uses the GPL 2.0 license. This work switches the dependency to [Rainbow](https://github.com/ku1ik/rainbow), which uses the MIT license, ensuring that NextRails also does not inherit the GPL license.
Some organizations are not allowed to use the GPL license. Switching to Rainbow allows others to use NextRails because it will no longer include a GPL dependency.
The change is relatively minimal, and Rainbow has a similar API to Colorize, albeit using Ruby Refinements. 
- Updated specs to ensure they pass
- Tested locally against a Rails project
> Use Rainbow to remove GPL dependency Colorize

- CHANGELOG.md
- README.md
- exe/bundle_report
- lib/next_rails.rb
- lib/next_rails/bundle_report.rb
- lib/next_rails/bundle_report/ruby_version_compatibility.rb
- lib/next_rails/gem_info.rb
- spec/next_rails/bundle_report/ruby_version_compatibility_spec.rb
Closes https://github.com/fastruby/next_rails/issues/115
Closes https://github.com/fastruby/next_rails/issues/17
Have an easy way to get the incompatible gems with a given ruby version.
Wrote some automated tests and Installed the gem locally
> [FEATURE] Add bundle_report compatibility --ruby-version  report

- CHANGELOG.md
- lib/next_rails/bundle_report/ruby_version_compatibility.rb
Call Rainbow instead of Colorize in `bundle_report/ruby_version_compatibility.rb`
Recentry the #120 PR removed Colorize in favor of Rainbow,
`bundle_report/ruby_version_compatibility.rb` was using Colorize and we need to update it to use Rainbow.
Some tests were failing because of this, now they are passing.
> Call Rainbow instead of Colorize

- .github/workflows/main.yml
- CHANGELOG.md
Ruby 2.0.0, 2.1, 2.2 does not support Rainbow 3, so, we are removing support for older Ruby versions.
Moving away of the Colorize dependency gem because it uses GPL 2.0 license.
https://github.com/fastruby/next_rails/pull/120
Running the test suite
> Remove older ruby tests

- CHANGELOG.md
- lib/next_rails/version.rb
Release version 1.4.0
We have enough features to release a new version.
Running the test suite.
> Release work for v1.4.0

- exe/bundle_report
- exe/deprecations
- lib/deprecation_tracker.rb
- lib/next_rails/bundle_report.rb
- lib/next_rails/bundle_report/ruby_version_compatibility.rb
- spec/next_rails/bundle_report_spec.rb
Use the Rainbow gem directly (i.e. `Rainbow("text").red`) instead of relying on the String monkey patching.
I checked for usage of the following methods:
- background
- bg
- black
- blink
- blue
- bold
- bright
- color
- cross_out
- cyan
- dark
- faint
- fg
- foreground
- green
- hide
- inverse
- italic
- magenta
- red
- reset
- strike
- underline
- white
- yellow
Those are the basic methods defined by the rainbow. I skipped the methods covered by the problematic "method_missing".
Fix https://github.com/fastruby/next_rails/issues/130
As raised in the https://github.com/fastruby/next_rails/issues/130, the release 1.4.0 impacted performance of a couple apps. The underlying issue is that the rainbow gem is refining the String class and that the `method_missing` is overwritten.
The `refine` …
> Use Rainbow directly instead of relying on String refinement.

- .github/workflows/main.yml
- CHANGELOG.md
- next_rails.gemspec
Ruby 3.4 is removing the `base64` default gem to [became bundled](https://rubyreferences.github.io/rubychanges/3.4.html#default-gems-that-became-bundled)
```
/Users/juan/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/webmock-3.16.2/lib/webmock.rb:14: warning: base64 was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add base64 to your Gemfile or gemspec to silence this warning.
```
Making the current webmock (v3.16.2) gem incompatible because it has a dependency on the `base64` gem,
to fix it we are bumping webmock to v3.20.0 which [removed the
`base64`](https://github.com/bblimke/webmock/pull/1046) dependency.
> [!NOTE]
> As an alternative solution, we can leave the current `webmock` version untoched
and add the …
> Add Ruby 3.4 support

- CHANGELOG.md
- exe/next.sh
- exe/next_rails
- lib/next_rails.rb
- lib/next_rails/init.rb
- spec/next_rails/init_spec.rb
1. I added a message to deprecate the current `next --init` command
(eventually, we should remove it).
2. Moved the `next --init` functionality into the `NextRails::Init` class
3. Still need to move the `bundle exec next` functionallity. (next step? depends on the acceptance of this PR).
If the user has the `next` command installed from `npm install -g next`, the `next --init` command will not work.
This is a problem because the user will not know how to call the `next` command.
It is reported here:
Closes https://github.com/fastruby/next_rails/issues/113
- I have tested this by running the `next --init` command and checking that the message is displayed.
- I have added automated tests to check the functionality of the `NextRails::Init` class.
Added a deprecation warning when running …
> Add next_rails --init to replace next --init

- CHANGELOG.md
- lib/next_rails/version.rb
Increase Ruby support, and deprecate the `next --init` command because it might cause some issues when the user has the `next` JS command installed.
> Release work for v1.4.3

- .github/workflows/main.yml
This is related to https://github.com/fastruby/next_rails/issues/135
Testing locally with Ruby 2.5 *just works* so I wanted to see if CI worked.
`bundle exec rake test`
N/A
> Test Ruby 2.5 in CI 

- CHANGELOG.md
- lib/deprecation_tracker.rb
- spec/deprecation_tracker_spec.rb
Since Rails 7.1 the preferred way to track deprecations is to access the deprecation trackers via `Rails.application.deprecators`.
Here, we change the implementation to use that if it is available, otherwise fallback to tracking deprecations via the `ActiveSupport::Deprecation` singleton object for older Rails versions.
Related Rails changes: 
- [Add Rails.application.deprecators](https://github.com/rails/rails/pull/46049#top)
- [Deprecate ActiveSupport::Deprecation singleton usage](https://github.com/rails/rails/pull/47354)
This is required to avoid getting deprecation warnings when using `next_rails` on Rails 7.1+ versions. 
```
DEPRECATION WARNING: Calling behavior on ActiveSupport::Deprecation is deprecated and will be removed from Rails (use Rails. …
```
> Update deprecation tracker to support newer Rails versions (7.1+)

- README.md
Replace `next --init` with `next_rails --init` in the README.md
Since we are deprecating `next --init`, let's stop mentioning it in the
README.md
It's just documentation change.
> Use next_rails --init in docs

- CHANGELOG.md
- exe/bundle_report
- lib/next_rails.rb
- lib/next_rails/bundle_report.rb
- lib/next_rails/bundle_report/rails_version_compatibility.rb
- spec/next_rails/bundle_report/rails_version_compatibility_spec.rb
- spec/next_rails/bundle_report/ruby_version_compatibility_spec.rb
- spec/next_rails/bundle_report_spec.rb
- spec/spec_helper.rb
I extracted it into its own class
I think it will be easier to understand the `BundleReport.compatibility` method and its usage
also I will need to use data from the `incompatible_gems_by_state` method in another code.
There was an existing test case for the `erb_output` method, and I run it locally to make sure it still works.
> Move bundle_report rails compatibility logic into a class

- CHANGELOG.md
- lib/next_rails/version.rb
Release work around the rails compatibility extraction.
I need to use the `incompatible_gems_by_state` from the rails incompatibility report outside of the gem, and the #137 is exposing it.
Running the test suite and added a few more tests.
> Release work for v1.4.5

- .gitignore
I just release a new gem and noticed that git was tracking the `.gem` binary file.
since we won't commit it by accident, I added it to the `.gitignore` file.
> Exclude .gem binary to be commited

- CHANGELOG.md
- lib/next_rails/gem_info.rb
- spec/next_rails/gem_info_spec.rb
Use fetcher instead of new when we use Gem::SpecFetcher
Fixes: https://github.com/fastruby/next_rails/issues/149
Use [fetcher](https://rubyapi.org/3.4/o/gem/specfetcher#method-c-fetcher) instead of new when we use Gem::SpecFetcher
Fixes: https://github.com/fastruby/next_rails/issues/149
Using `time` before and after:
- Before: `42.34s user 1.83s system 97% cpu 45.095 total`
- After: `5.68s user 0.61s system 72% cpu 8.728 total`
Using automated tests.
Using stack prof:
| Before | After |
| - | - |
| ![image](https://github.com/user-attachments/assets/c1ea2e8f-1289-4588-b1cd-6b830164d6b5)  |  ![image](https://github.com/user-attachments/assets/eba61493-fc91-49eb-90b9-99fbb801c81e)  |
**I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md)* …
> BUG-149: Fix compatibilities performance bug

- .github/workflows/main.yml
- CHANGELOG.md
- lib/next_rails/bundle_report/cli.rb
- next_rails.gemspec
This PR attempts to add back support of Ruby 2.3, 2.4, and 2.5 as requested in #135.
To add back the support for the older Ruby versions, I had to make the following changes:
- Several months ago, `rexml` was updated in this commit https://github.com/fastruby/next_rails/commit/e50e05a0d5e11124e48e8bfc89737e82f2c9bd83 . I had to downgrade it to 3.2.5, as 3.2.6 and above set Ruby 2.5 as the minimum requirement as seen in `rexml`’s `gemspec` https://github.com/ruby/rexml/commit/072b02fdcf4993e61cb39f4ed545f77e2f98d3d5.
- We added Ruby 3.4 support in February: https://github.com/fastruby/next_rails/commit/816e5b6434811fc766a0da2219b78b28598708aa by updating `webmock` to `3.20.0`. `webmock` version `3.20.0` is incompatible with Ruby versions below 2.5. To keep support for both Ruby 3.4 and …
> Bring back support of Ruby 2.3, 2.4 and 2.5

- CHANGELOG.md
- lib/deprecation_tracker.rb
- lib/next_rails/version.rb
- spec/deprecation_tracker_spec.rb
[STJ-23: BUGFIX: deprecation_tracker breaking with unknown keywords](https://ombulabs.atlassian.net/browse/STJ-23)
BUGFIX: Prevent DeprecationTracker from crashing when receiving unknown keyword arguments.
In certain environments (e.g. when using sass-embedded), the warn method receives unexpected keyword arguments such as :deprecation, :span, or :stack. Previously, these unrecognized keywords would raise an ArgumentError and interrupt execution. This patch safely handles unknown keyword arguments while preserving known ones.
Fixes [#152](https://github.com/fastruby/next_rails/issues/152) — DeprecationTracker was breaking during setup in projects using sass-embedded due to unhandled keyword arguments in warn.
This update ensures that warn forwards all known and unknown keyword arguments …
> STJ-23: BUGFIX: deprecation_tracker breaking with unknown keywords #157
